index:
    path: /
    controller: App\Controller\HomeController::index
user:
    path: /user
    controller: App\Controller\UserController::index
registro_usuarios:
    path: /register
    controller: App\Controller\RegistrationController::register
registro_admin:
    path: /registerAdmin
    controller: App\Controller\RegistrationController::registerAdmin  
preferencias:
    path: /preferencias
    controller: App\Controller\PreferenciasController::index
ciudad:
    path: /ciudad
    controller: App\Controller\PreferenciasController::index
foto:
    path: /foto
    controller: App\Controller\FotoController::index

